package main

import "encoding/binary"

func unpacker3(data []byte) ([]byte, []uint32) {
	regs := [4]uint32{}
	ret := []uint32{}
	pulloverBits := func(n uint8) {
		remainderMask := bitsToMask(n)
		leftoverMask := bitsToMask(10 - n)
		remainder := [4]uint32{regs[0], regs[1], regs[2], regs[3]}
		regs[0] = (binary.LittleEndian.Uint32(data[0:4]))
		data = data[4:]
		regs[0] = (binary.LittleEndian.Uint32(data[0:4]))
		data = data[4:]
		regs[0] = (binary.LittleEndian.Uint32(data[0:4]))
		data = data[4:]
		regs[0] = (binary.LittleEndian.Uint32(data[0:4]))
		data = data[4:]
		fromPrevious := (remainder[0] & remainderMask)
		cur := ((regs[0] & leftoverMask) << n)
		ret = append(ret, ret[len(ret)-4]+(cur|fromPrevious))
		ret = append(ret, ret[len(ret)-4]+(((regs[1]&leftoverMask)<<n)|(remainder[1]&remainderMask)))
		ret = append(ret, ret[len(ret)-4]+(((regs[2]&leftoverMask)<<n)|(remainder[2]&remainderMask)))
		ret = append(ret, ret[len(ret)-4]+(((regs[3]&leftoverMask)<<n)|(remainder[3]&remainderMask)))
		regs[0] >>= 3 - n
		regs[1] >>= 3 - n
		regs[2] >>= 3 - n
		regs[3] >>= 3 - n
	}
	{
		mask := bitsToMask(3)
		regs[0] = (binary.LittleEndian.Uint32(data[0:4]))
		data = data[4:]
		regs[1] = (binary.LittleEndian.Uint32(data[0:4]))
		data = data[4:]
		regs[2] = (binary.LittleEndian.Uint32(data[0:4]))
		data = data[4:]
		regs[3] = (binary.LittleEndian.Uint32(data[0:4]))
		data = data[4:]
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x1))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x4))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x7))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xa))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xd))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x10))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x13))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x16))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x19))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x1c))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x1f))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x22))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x25))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x28))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x2b))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x2e))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x31))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x34))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x37))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x3a))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x3d))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x40))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x43))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x46))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x49))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x4c))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x4f))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x52))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x55))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x58))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x5b))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x5e))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x61))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x64))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x67))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x6a))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x6d))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x70))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x73))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x76))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x79))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x7c))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x7f))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x82))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x85))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x88))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x8b))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x8e))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x91))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x94))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x97))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x9a))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x9d))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xa0))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xa3))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xa6))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xa9))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xac))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xaf))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xb2))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xb5))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xb8))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xbb))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xbe))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xc1))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xc4))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xc7))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xca))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xcd))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xd0))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xd3))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xd6))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xd9))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xdc))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xdf))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x3))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x6))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x9))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xc))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0xf))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x12))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x15))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x18))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x1b))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x1e))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x21))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x24))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x27))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x2a))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x2d))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x30))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x33))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x36))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x39))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x3c))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x3f))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x42))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x45))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x48))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x4b))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x4e))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x51))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x54))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x57))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x5a))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x5d))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
		pulloverBits(uint8(0x60))
		ret = append(ret, regs[0]&mask)
		ret = append(ret, regs[1]&mask)
		ret = append(ret, regs[2]&mask)
		ret = append(ret, regs[3]&mask)
	}
	return data, ret
}
